# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e19e9ad82ebd785b6df6ec2b3bcfcb704da69de659e2d61feecde0dd3144e9152a60cfc3aa1b96d76064ea6135a5fcfdf9ce0e739104616ade05dcea9c6a226

test:
  secret_key_base: 344237c4bbdf8fdc5ac375e47782eccdf332425fde5c599db8a1641621035228479133a86975bcaa6f6cde7d99d3203862ecb17eb81c88b29f4502d114bae9f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
